# Самостоятельная работа 2. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np


print(np.__version__)

1.23.3


2) Создать нулевой вектор размера 10

In [2]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [4]:
a = 7 * np.ones(7)
print(a)

[7. 7. 7. 7. 7. 7. 7.]


4) Создать вектор заполненный четными числами от 10 до 100

In [17]:
a = np.linspace(10, 100, num=(100 - 10) // 2 + 1, dtype=int)
print(a)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [19]:
a = np.random.randint(0, 10, 10)
print(a)

a = a[::-1]
print(a)

[3 9 0 4 0 3 1 8 3 7]
[7 3 8 1 3 0 4 0 9 3]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

> От 0 до 9 располагается 10 цифр, а в матрицу 3х3 можно уместить только 9. Наверное полагалось от 1 до 9 

In [32]:
a = np.linspace(1, 9, num=9, dtype=int).reshape(3, 3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [178]:
a = np.zeros((4, 4))

for i in range(0, len(a)):
    if i >= len(a) -1:
        continue
    else:
        a[i][i + 1] = 1

print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [161]:
a = 7 * np.ones((4, 4))
np.fill_diagonal(a, [i for i in range(1, 5)])
print(a)

[[1. 7. 7. 7.]
 [7. 2. 7. 7.]
 [7. 7. 3. 7.]
 [7. 7. 7. 4.]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [46]:
a = np.array([[i for i in range (0, 5)] for _ in range(5)])
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [57]:
a = np.random.randint(0, 100, (10, 10))
print(a)

a = a - a.mean(axis=1)

print(a)

[[16 34 54 34 35 89 17  7 37 67]
 [82 91 46 50  5 81 79 36 67 34]
 [ 0 74 72 32 94 92  1 69 85 75]
 [54 26 42 98 35 72 63 80 50 92]
 [ 3 51  2 78 75 22 19 89 67 34]
 [47 51 46 43 44 42 75 75 30 78]
 [ 2 38  2 28 17 80 37 44 50  6]
 [32 87 66 89 78 27 91 84 92 98]
 [72 59 89 24 49 95 21 10  0 66]
 [87 36 13 59 38 84 15 46 90 35]]
[[-23.  -23.1  -5.4 -27.2  -9.   35.9 -13.4 -67.4 -11.5  16.7]
 [ 43.   33.9 -13.4 -11.2 -39.   27.9  48.6 -38.4  18.5 -16.3]
 [-39.   16.9  12.6 -29.2  50.   38.9 -29.4  -5.4  36.5  24.7]
 [ 15.  -31.1 -17.4  36.8  -9.   18.9  32.6   5.6   1.5  41.7]
 [-36.   -6.1 -57.4  16.8  31.  -31.1 -11.4  14.6  18.5 -16.3]
 [  8.   -6.1 -13.4 -18.2   0.  -11.1  44.6   0.6 -18.5  27.7]
 [-37.  -19.1 -57.4 -33.2 -27.   26.9   6.6 -30.4   1.5 -44.3]
 [ -7.   29.9   6.6  27.8  34.  -26.1  60.6   9.6  43.5  47.7]
 [ 33.    1.9  29.6 -37.2   5.   41.9  -9.4 -64.4 -48.5  15.7]
 [ 48.  -21.1 -46.4  -2.2  -6.   30.9 -15.4 -28.4  41.5 -15.3]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [70]:
a = np.random.randint(0, 10, (10, 10))
print(a)

a = a - np.median(a, axis=0)

print(a)

[[2 1 5 2 3 8 0 3 9 9]
 [2 2 5 7 3 1 8 8 4 0]
 [9 6 1 7 0 6 4 4 0 0]
 [1 3 2 8 8 5 2 3 8 3]
 [7 9 3 6 4 7 2 9 4 3]
 [0 3 9 4 7 9 5 1 0 3]
 [8 3 0 8 2 3 9 2 6 1]
 [6 6 3 3 9 7 4 4 8 2]
 [8 1 5 4 8 7 8 3 3 1]
 [0 7 9 0 5 7 9 8 3 8]]
[[-2.  -2.   1.  -3.  -1.5  1.  -4.5 -0.5  5.   6.5]
 [-2.  -1.   1.   2.  -1.5 -6.   3.5  4.5  0.  -2.5]
 [ 5.   3.  -3.   2.  -4.5 -1.  -0.5  0.5 -4.  -2.5]
 [-3.   0.  -2.   3.   3.5 -2.  -2.5 -0.5  4.   0.5]
 [ 3.   6.  -1.   1.  -0.5  0.  -2.5  5.5  0.   0.5]
 [-4.   0.   5.  -1.   2.5  2.   0.5 -2.5 -4.   0.5]
 [ 4.   0.  -4.   3.  -2.5 -4.   4.5 -1.5  2.  -1.5]
 [ 2.   3.  -1.  -2.   4.5  0.  -0.5  0.5  4.  -0.5]
 [ 4.  -2.   1.  -1.   3.5  0.   3.5 -0.5 -1.  -1.5]
 [-4.   4.   5.  -5.   0.5  0.   4.5  4.5 -1.   5.5]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [83]:
a = np.random.randint(0, 100, (10, 10))

print(a)

max_col_values, min_col_values = np.max(a, axis=1), np.min(a, axis=1)

a = np.append(a, np.array([max_col_values, min_col_values]).T, axis=1)
print(a)

[[ 0 33 95  3 32 82 86 84 88 81]
 [91 62 87 79  0 62 72 22 87 26]
 [55  0 38 36 19 72 41 50 92 75]
 [10 12 58 61  6 97 85 54 91  9]
 [64 27 46 88 83 41 44 43 81 73]
 [75 54 21 68 99 10 21 12 69 16]
 [37 11 78 65 24 74 71 76 34 80]
 [64 88 87 33 73 70 23 52 48 29]
 [66 68  1 13 14 95 46 98 67 35]
 [43 19  0 64 46 35 24 17  4 30]]
[[ 0 33 95  3 32 82 86 84 88 81 95  0]
 [91 62 87 79  0 62 72 22 87 26 91  0]
 [55  0 38 36 19 72 41 50 92 75 92  0]
 [10 12 58 61  6 97 85 54 91  9 97  6]
 [64 27 46 88 83 41 44 43 81 73 88 27]
 [75 54 21 68 99 10 21 12 69 16 99 10]
 [37 11 78 65 24 74 71 76 34 80 80 11]
 [64 88 87 33 73 70 23 52 48 29 88 23]
 [66 68  1 13 14 95 46 98 67 35 98  1]
 [43 19  0 64 46 35 24 17  4 30 64  0]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

> в обычном смысле обратная матрица не существует - только псевдообратая
>
> вероятно дело в условие или в его понимание

In [23]:
a = np.linspace(1, 50, 50)

even_vect = np.array([el for el in a if el % 2 == 0]).reshape((-1, 1))
odd_vect = np.array([el for el in a if el % 2 != 0]).reshape((1, -1))

mul = even_vect @ odd_vect

inv = np.linalg.pinv(mul)

print(inv)

[[4.34562965e-09 8.69125931e-09 1.30368890e-08 1.73825186e-08
  2.17281483e-08 2.60737779e-08 3.04194076e-08 3.47650372e-08
  3.91106669e-08 4.34562965e-08 4.78019262e-08 5.21475559e-08
  5.64931855e-08 6.08388152e-08 6.51844448e-08 6.95300745e-08
  7.38757041e-08 7.82213338e-08 8.25669634e-08 8.69125931e-08
  9.12582227e-08 9.56038524e-08 9.99494821e-08 1.04295112e-07
  1.08640741e-07]
 [1.30368890e-08 2.60737779e-08 3.91106669e-08 5.21475559e-08
  6.51844448e-08 7.82213338e-08 9.12582227e-08 1.04295112e-07
  1.17332001e-07 1.30368890e-07 1.43405779e-07 1.56442668e-07
  1.69479557e-07 1.82516445e-07 1.95553334e-07 2.08590223e-07
  2.21627112e-07 2.34664001e-07 2.47700890e-07 2.60737779e-07
  2.73774668e-07 2.86811557e-07 2.99848446e-07 3.12885335e-07
  3.25922224e-07]
 [2.17281483e-08 4.34562965e-08 6.51844448e-08 8.69125931e-08
  1.08640741e-07 1.30368890e-07 1.52097038e-07 1.73825186e-07
  1.95553334e-07 2.17281483e-07 2.39009631e-07 2.60737779e-07
  2.82465928e-07 3.04194076e-07 3.

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

> 1 - белые 
>
> 0 - черные

In [126]:
a = np.tile([0, 1], 32).reshape(8, 8)

for i in range(0, len(a), 2):
    a[i] = np.roll(a[i], 1)

print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
